apiVersion: v1
data:
  ENABLE_ALPHA: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: 8743ea5c-bca5-4a19-84e2-1aa53967ef5b
  name: alpha-features-6992b4959t
  namespace: prod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: 8743ea5c-bca5-4a19-84e2-1aa53967ef5b
  name: gke-flask-app
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
    env: prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: 8743ea5c-bca5-4a19-84e2-1aa53967ef5b
  name: gke-flask-app
  namespace: prod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask
      env: prod
  template:
    metadata:
      labels:
        app: flask
        app.kubernetes.io/managed-by: skaffold
        env: prod
        skaffold.dev/run-id: 8743ea5c-bca5-4a19-84e2-1aa53967ef5b
    spec:
      containers:
      - env:
        - name: ENABLE_ALPHA
          valueFrom:
            configMapKeyRef:
              key: ENABLE_ALPHA
              name: alpha-features-6992b4959t
        image: gcr.io/kenthua-core/gke-flask-app:9c4fc26@sha256:59584f5705c3ecc8022bddcb7d490556b8a72e2cb99e0a46c3769358ae45aa28
        imagePullPolicy: IfNotPresent
        name: gke-flask-app
        ports:
        - containerPort: 5000
