apiVersion: v1
data:
  ENABLE_ALPHA: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 853c8980-0907-4edb-9905-c52f53dd4fa7
    skaffold.dev/tag-policy: custom
  name: alpha-features-6992b4959t
  namespace: prod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 853c8980-0907-4edb-9905-c52f53dd4fa7
    skaffold.dev/tag-policy: custom
  name: gke-flask-app
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
    env: prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 853c8980-0907-4edb-9905-c52f53dd4fa7
    skaffold.dev/tag-policy: custom
  name: gke-flask-app
  namespace: prod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask
      env: prod
  template:
    metadata:
      labels:
        app: flask
        app.kubernetes.io/managed-by: skaffold-v1.12.1
        env: prod
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/profile.0: prod
        skaffold.dev/run-id: 853c8980-0907-4edb-9905-c52f53dd4fa7
        skaffold.dev/tag-policy: custom
    spec:
      containers:
      - env:
        - name: ENABLE_ALPHA
          valueFrom:
            configMapKeyRef:
              key: ENABLE_ALPHA
              name: alpha-features-6992b4959t
        image: gcr.io/agmsb-k8s/gke-flask-app:39534a1@sha256:24e8d64fcb4aa5ac36d0cf66c36e349e740da53d3932787a24d0d01f8072b392
        imagePullPolicy: IfNotPresent
        name: gke-flask-app
        ports:
        - containerPort: 5000
