apiVersion: v1
data:
  enableAlpha: "false"
kind: ConfigMap
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 27aa3d47-efa3-4eaf-b72f-dbee6f64bec7
    skaffold.dev/tag-policy: custom
  name: alpha-features
  namespace: prod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 27aa3d47-efa3-4eaf-b72f-dbee6f64bec7
    skaffold.dev/tag-policy: custom
  name: gke-flask-app
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
    env: prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 27aa3d47-efa3-4eaf-b72f-dbee6f64bec7
    skaffold.dev/tag-policy: custom
  name: gke-flask-app
  namespace: prod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask
      env: prod
  template:
    metadata:
      labels:
        app: flask
        app.kubernetes.io/managed-by: skaffold-v1.12.1
        env: prod
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/profile.0: prod
        skaffold.dev/run-id: 27aa3d47-efa3-4eaf-b72f-dbee6f64bec7
        skaffold.dev/tag-policy: custom
    spec:
      containers:
      - env:
        - name: ENABLE_ALPHA
          valueFrom:
            configMapKeyRef:
              key: enableAlpha
              name: alpha-features
        image: gcr.io/agmsb-k8s/gke-flask-app:a21eaac@sha256:5af276feb0bb3fab97de618d5b064897acd3df118e8cdd7d195d6d9880c58865
        imagePullPolicy: IfNotPresent
        name: gke-flask-app
        ports:
        - containerPort: 5000
