apiVersion: v1
data:
  enableAlpha: "false"
kind: ConfigMap
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 055cd1c7-03a8-4404-aafb-e2ff969f4f2e
    skaffold.dev/tag-policy: git-commit
  name: prod-alpha-features
  namespace: prod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 055cd1c7-03a8-4404-aafb-e2ff969f4f2e
    skaffold.dev/tag-policy: git-commit
  name: prod-gke-flask-app
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
    env: prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
    app.kubernetes.io/managed-by: skaffold-v1.12.1
    env: prod
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: prod
    skaffold.dev/run-id: 055cd1c7-03a8-4404-aafb-e2ff969f4f2e
    skaffold.dev/tag-policy: git-commit
  name: prod-gke-flask-app
  namespace: prod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask
      env: prod
  template:
    metadata:
      labels:
        app: flask
        app.kubernetes.io/managed-by: skaffold-v1.12.1
        env: prod
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/profile.0: prod
        skaffold.dev/run-id: 055cd1c7-03a8-4404-aafb-e2ff969f4f2e
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - env:
        - name: ENABLE_ALPHA
          valueFrom:
            configMapKeyRef:
              key: enableAlpha
              name: prod-alpha-features
        image: gcr.io/agmsb-k8s/gke-flask-app:latest@sha256:97b6b32038cb402d8bea6ab1c6976dc9837d5ee55ec8eba571c172cd2d455027
        imagePullPolicy: IfNotPresent
        name: gke-flask-app
        ports:
        - containerPort: 5000
