steps:
- id: gke-deploy-prod
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
    - 'run'
    - '-f'
    - './resources.yaml'
    - '--label=deploy-sha=${SHORT_SHA}'
    - '--location=us-west1'
    - '--cluster=oregon'